### ISSUE TITLE
Logic

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Thermal-Incubator#1]
I was at the lab earlier today to check if this works, but I couldn't get the heater to connect properly. Guess I'll have to do that next class.

But does this seem alright? I think it should cover all the cases?

**Comment by davidbradway** [comment]
The logic looks good. A couple suggestions:
To be really explicit you could use just 'if' and' else' for each exclusive comparison. Right now you catch < and > but not == (which doesn't happen much with floating point comparisons, but it is cleaner to have cases for all conditions and explicitly say you are choosing to do nothing if that's what you intend). You could also simplify comparisons since both cases in your lower alarm comparisons have the same outputs.

**Comment by davidbradway** [comment]
You could also add Serial print commands to debug and document the states you are entering. Regarding the relay, you are still powering it, the Hester, and the MOSFET, right? And using the same ground for your Arduino and other circuit components?

**Comment by a-poorva** [comment]
Thank you for your help! I made a couple of changes: does it look better? 

As for the relay, I was definitely powering all the components correctly, but I don't remember how exactly I connected the ground. I'll have to redo that bit in class.

**Comment by davidbradway** [comment]
Your "else" clause (line 51) isn't structured correctly (else has no conditions -- nothing after the "{" ). 
And your last "if" statement doesn't make sense (you have two incompatible statements ANDed together).
I think the last "if" statement can be turned into an "else" paired with the "if" on line 46. 
We can look at this Tuesday

**Comment by a-poorva** [comment]
Ahh wait I see the problem. I'll look into how I can make the code a little more elegant.

Thanks for your help, and have a happy thanksgiving!
